#!/bin/bash
# ALMKA Blind - Render Deployment Quick Start Script
# Copy and paste commands below one by one into your terminal

echo "========================================"
echo "ALMKA Render Deployment - Quick Start"
echo "========================================"
echo ""
echo "STEP 1: Prepare Your Local Project"
echo "========================================"
echo "Run these commands in: C:\xampp\htdocs\ALMKA_Blind"
echo ""
echo "# Check git status"
echo "git status"
echo ""
echo "# If there are changes, commit them"
echo "git add ."
echo "git commit -m 'Prepare for Render deployment'"
echo ""
echo ""
echo "STEP 2: Optimize for Production"
echo "========================================"
echo ""
echo "# Cache configuration"
echo "php artisan config:cache"
echo ""
echo "# Cache routes"
echo "php artisan route:cache"
echo ""
echo "# Cache views"
echo "php artisan view:cache"
echo ""
echo "# Build frontend"
echo "npm run build"
echo ""
echo ""
echo "STEP 3: Commit and Push to GitHub"
echo "========================================"
echo ""
echo "git add ."
echo "git commit -m 'Production optimization: config/route/view cache'"
echo "git push origin main"
echo ""
echo ""
echo "STEP 4: Go to Render Dashboard"
echo "========================================"
echo ""
echo "1. Visit https://render.com/dashboard"
echo "2. Click '+ New'"
echo "3. Click 'Web Service'"
echo "4. Click 'Connect a Repository'"
echo "5. Select 'almka-blind'"
echo "6. Click 'Connect'"
echo ""
echo ""
echo "STEP 5: Configure Web Service Settings"
echo "========================================"
echo ""
echo "Name:          almka-blind"
echo "Environment:   PHP"
echo "Plan:          Free"
echo ""
echo "Build Command:"
echo "composer install --no-dev && npm install && npm run build"
echo ""
echo "Start Command:"
echo "php artisan migrate --force && php artisan storage:link && php artisan serve --host 0.0.0.0 --port \$PORT"
echo ""
echo ""
echo "STEP 6: Create PostgreSQL Database"
echo "========================================"
echo ""
echo "1. Click '+ New' from Render dashboard"
echo "2. Click 'PostgreSQL'"
echo "3. Name:    almka-blind-db"
echo "4. Version: 15"
echo "5. Plan:    Free"
echo "6. Click 'Create Database'"
echo ""
echo "7. Wait ~1 minute for database to be ready"
echo "8. Copy these credentials:"
echo "   - Hostname → DB_HOST"
echo "   - Port (5432) → DB_PORT"
echo "   - Database (almka_blind) → DB_DATABASE"
echo "   - User → DB_USERNAME"
echo "   - Password → DB_PASSWORD"
echo ""
echo ""
echo "STEP 7: Generate APP_KEY Locally"
echo "========================================"
echo ""
echo "# Run this on your Windows machine:"
echo "php artisan key:generate --show"
echo ""
echo "# Copy the output (looks like): base64:XXXXX"
echo ""
echo ""
echo "STEP 8: Add Environment Variables to Render"
echo "========================================"
echo ""
echo "In Render Web Service dashboard:"
echo "Click 'Environment' tab"
echo "Add each variable:"
echo ""
echo "  APP_NAME=ALMKA"
echo "  APP_ENV=production"
echo "  APP_DEBUG=false"
echo "  APP_KEY=base64:YOUR_KEY_FROM_STEP_7"
echo "  APP_URL=https://almka-blind.onrender.com"
echo "  LOG_CHANNEL=stack"
echo "  DB_CONNECTION=pgsql"
echo "  DB_HOST=YOUR_DATABASE_HOST"
echo "  DB_PORT=5432"
echo "  DB_DATABASE=almka_blind"
echo "  DB_USERNAME=YOUR_DATABASE_USER"
echo "  DB_PASSWORD=YOUR_DATABASE_PASSWORD"
echo "  CACHE_STORE=database"
echo "  QUEUE_CONNECTION=database"
echo "  SESSION_DRIVER=database"
echo "  FILESYSTEM_DISK=local"
echo "  VITE_API_BASE_URL=/api"
echo ""
echo ""
echo "STEP 9: Wait for Deployment"
echo "========================================"
echo ""
echo "Render will automatically start building!"
echo "Wait for status to change from 'Building' to 'Live'"
echo ""
echo "This takes 2-5 minutes."
echo ""
echo ""
echo "STEP 10: Test Your App"
echo "========================================"
echo ""
echo "Visit: https://almka-blind.onrender.com"
echo ""
echo "You should see:"
echo "✓ ALMKA login page"
echo "✓ No error messages"
echo "✓ Database is connected"
echo ""
echo ""
echo "STEP 11: Enable GitHub Auto-Deploy"
echo "========================================"
echo ""
echo "1. In Render dashboard, click 'Settings'"
echo "2. Find 'Deploy Hook' section"
echo "3. Copy the URL"
echo "4. Go to GitHub: https://github.com/alonzoaljon-dev/almka-blind"
echo "5. Click 'Settings' → 'Webhooks' → 'Add webhook'"
echo "6. Paste the URL"
echo "7. Content type: application/json"
echo "8. Click 'Add webhook'"
echo ""
echo "Done! Now every git push auto-deploys!"
echo ""
echo ""
echo "========================================"
echo "TROUBLESHOOTING"
echo "========================================"
echo ""
echo "If deployment fails:"
echo "1. Click 'Logs' in Render dashboard"
echo "2. Look for ERROR messages"
echo "3. Common errors:"
echo "   - 'npm: command not found' → Add package.json to project"
echo "   - 'composer: command not found' → Add composer.json to project"
echo "   - 'Killed' → Free tier memory limit hit"
echo "   - Database error → Check credentials"
echo ""
echo "If app shows blank page:"
echo "1. Open browser dev tools (F12)"
echo "2. Check Console tab for errors"
echo "3. Check Network tab for failed requests"
echo "4. Click 'Logs' in Render to see server errors"
echo ""
echo ""
echo "QUICK COMMANDS FOR RENDER SHELL"
echo "========================================"
echo ""
echo "# Access Render Shell (in Web Service dashboard)"
echo "# Run migrations if needed:"
echo "php artisan migrate --force"
echo ""
echo "# Test database connection:"
echo "php artisan tinker"
echo ">>> DB::table('users')->count()"
echo ""
echo "# Clear cache if needed:"
echo "php artisan cache:clear"
echo ""
echo "# View logs:"
echo "tail -f storage/logs/laravel.log"
echo ""
echo ""
echo "========================================"
echo "DEPLOYMENT COMPLETE! 🎉"
echo "========================================"
